server:
  port: 8080

spring:
  liquibase:
    change-log: classpath:/liquibase/master.xml
    enabled: true
  #启动配置
  profiles:
    active: local
  #freemarker
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates/

# 数据库日志打印
logging:
  level:
    com.gsean.dao: debug
  config: classpath:logback/logback-local.xml