server:
  port: 8082


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_base?serverTimezone=GMT&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
