server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_base?serverTimezone=GMT&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#    redis-config start
  redis:
    #redis数据库索引默认0
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
#     redis-config end

shiro:
  web:
    enable: true

config:
  #jwt认证加密私钥
  encrypt-jwtKey: U0JBUElOENhspJrzkyNjQ1NA
  #accessToken过期时间（秒）
  accessToken-expireTime: 600
  #refreshToken过期时间（秒）
  refreshToken-expireTime: 604800

